CREATE TABLE IF NOT EXISTS users (
     id INTEGER IDENTITY PRIMARY KEY,
     username VARCHAR(30) UNIQUE,
     password VARCHAR(30) NOT NULL,
     email VARCHAR(60) UNIQUE,
     description VARCHAR(300),
     reputation INT,
     date_joined TIMESTAMP
     /*icon bytea */
);

CREATE TABLE IF NOT EXISTS languages (
 id INTEGER IDENTITY PRIMARY KEY,
 name VARCHAR(30) UNIQUE
);

CREATE TABLE IF NOT EXISTS tags (
id INTEGER IDENTITY PRIMARY KEY,
name VARCHAR(30) UNIQUE
);

CREATE TABLE IF NOT EXISTS snippets (
    id INTEGER IDENTITY PRIMARY KEY,
    user_id INT REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL,
    title VARCHAR(50),
    description VARCHAR(500),
    code VARCHAR(6000),
    date_created TIMESTAMP ,
    language_id INT REFERENCES languages(id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS votes_for (
 user_id INT REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL,
 snippet_id INT REFERENCES snippets(id) ON UPDATE CASCADE ON DELETE CASCADE,
 type INT,
 CONSTRAINT one_snippet_one_vote PRIMARY KEY(user_id, snippet_id)
);

CREATE TABLE IF NOT EXISTS favorites (
     snippet_id INT REFERENCES snippets(id) ON UPDATE CASCADE ON DELETE CASCADE,
     user_id INT REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
     PRIMARY KEY(snippet_id, user_id)
);

CREATE TABLE IF NOT EXISTS follows (
   user_id INT REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
   tag_id INT REFERENCES tags(id) ON UPDATE CASCADE ON DELETE CASCADE,
   PRIMARY KEY(user_id, tag_id)
);

CREATE TABLE IF NOT EXISTS snippet_tags (
    snippet_id INT REFERENCES snippets(id) ON UPDATE CASCADE ON DELETE CASCADE,
    tag_id INT REFERENCES tags(id) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY(snippet_id, tag_id)
);
